# -*- coding: utf-8 -*-
"""Unit2_Loop_Assignment_3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nQcLPA6IWWO2N8fgdPW61-EVWb36nRSh

<a href="https://colab.research.google.com/github/niteen11/lagcc_data_analytics_micro_credential/blob/master/Unit%202%20-%20Python%20Fundamentals/Assignments/Unit2_Loop_Assignment_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Intrdouction to Python - Loop - Assignment #3

## 1. Create a list that holds 5 data variables.
"""

#list with 5 data

data = (5, 10, 15, 20, 25)

"""## 2.	Print out those variables by using a for loop"""

#print the variables
for x in data: 
  print(x)



"""## 3.	Modify your for loop to add a message to your for loop."""

for x in data:
  print(str(x) + " is divisible by five")



"""## 4.	Use a for loop to print even numbers from 1-20."""

for num in range(1,21):
  if num % 2 == 0:
    print(num)



"""## 5.	Sort your list in alphabetic order."""

#sort ABC order
list_2 = ["ancient gate of throw", "old gates of throw", "new gate of throws", "no gate of throw"]

sorted(list_2)



"""## 6.	Print out the first three elements of your list."""

print("Some good names for TV shows: ")
for goodnames in list_2[:3]:
  print(goodnames)



"""## 7.	Create a loop to print the last 2 elements of your list."""

print("Some good names for TV shows: ")
for goodnames in list_2[2:]:
  print(goodnames)

