# -*- coding: utf-8 -*-
"""Unit2_Intro_Assignment_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17MdvcTf3Rr9WEmBo1VHuKEkT67AdKbSI

<a href="https://colab.research.google.com/github/niteen11/lagcc_data_analytics_micro_credential/blob/master/Unit%202%20-%20Python%20Fundamentals/Assignments/Unit2_Intro_Assignment_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Lesson 1 - Intrdouction to Python - Assignment 1

> Indented block

## 1.	What is Python and why is it useful?

relative simply but very powerful programming language

## 2.	Are the following variable names allowed in python?

a.	1_message

b.	Greeting_message

c.	Message_1

d.	First name

e.	Full_name

b,c and d

## 3.	Create a variable that holds the string “hello there!”
"""

print(str("hello there!"))



"""## 4.	Create a variable for first name, last name and an email extension.  Concatenating all three together to form an email address.  For example: firstnamelastname@gmail.com"""

#create a variable
#cocatenate variable to email
first_name = input("What is your first name: ")
last_name = input("What is your last name: ")
email_extension = input("What is your email extension: ")
email_address = first_name + last_name + email_extension
print(email_address)



"""## 5.	Store someone you know name in a variable called name.  Print their name in lower and uppercase using a method."""

#store a variable called name
#print in lower and uppercase of someone's name
name = "Angel"
print(name.upper())
print(name.lower())



