# -*- coding: utf-8 -*-
"""Unit2_Mini_Project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HGpM05Uti3g-kD9b1dglVRVRtOl3ZOIH

<a href="https://colab.research.google.com/github/niteen11/lagcc_data_analytics_micro_credential/blob/master/Unit%202%20-%20Python%20Fundamentals/Mini%20Project/Unit2_Mini_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Intrdouction to Python - Mini Project

#Python Project – Odd or Even

Ask the user for a number. Depending on whether the number is even or odd, print out an appropriate message to the user. Hint: how does an even / odd number react differently when divided by 2?
"""

#ask the user for a number
#determine if the number is even or odd
#print message on if the number is even or odd

number = int(input("Give me a number: "))

reminder = number % 2

if reminder == 0:
  print("The number is even :)")
else:
  print("The number is odd!")

#check if a number is a multiple of 4
#print message for multiple of 4
multiple = number % 4

if multiple == 0:
  print("Yes! The number is a multiple of four")
else:
  print("Oops! The number is not a multiple of four")





"""# Bonus:

1.	If the number is a multiple of 4, print out a different message.

2.	Ask the user for two numbers: one number to check (call it num) and one number to divide by (check). If check divides evenly into num, tell that to the user. If not, print a different appropriate message.

"""

#ask the user for 2 numbers, num and check
#num to check and check to divide by
#See if check is fully divided by num
#print result 
num = int(input("Give me one number: "))
check = int(input("Give me another number: "))

residue = num % check

if residue == 0:
  print(str(num) + " is the multiple of " + str(check))
else:
  print(str(num) + " is not the multiple of " + str(check))





