# -*- coding: utf-8 -*-
"""Unit2_Conditional_Operations_Assignment_4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hP0X5Xc4z33SHflpK8lg_48eicKGU8eA

<a href="https://colab.research.google.com/github/niteen11/lagcc_data_analytics_micro_credential/blob/master/Unit%202%20-%20Python%20Fundamentals/Assignments/Unit2_Conditional_Operations_Assignment_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Intrdouction to Python - Conditional Operations Assignment #4

## If-elif-else Statements

## 1.	Make a list of 5 or more usernames, including an admin account.  Imagine you are writing code that will welcome people to your application on login. Loop through the list and print your greeting.

a.	If the admin account logs in, give them a special greeting.  They’re the admin, after all!

b.	Other users can get the generic greeting
"""

#make a list with 5 or more usernames(one being an admin account)
#Loop the list
#print greeting for the users(generic greeting) and admin(special greeting)

list_1 = ("popmind", "pophand", "popfeet", "pophead", "popmouth", "popadmin")

for names in list_1:
  if names == "popadmin":
    print("Hello Admin, Welcome!")
  else:
    print("Hello " + names + ", Welcome!")











"""## 2.	Store numbers 1-10 in a list

a.	Loop through the list

b.	Use an if-elif-else chain inside your loop to print the ordinal ending for each number – for example – 1st, 2nd, 3rd … etc.


"""

#store number 1-10 in a list
#loop the list
#print numbers with ordinal ending

for number in range (1,11):
  if number == 1:
    print(str(number) + "st")
  elif number == 2:
    print(str(number) + "nd")
  elif number == 3:
    print(str(number) + "rd")
  else:
    print(str(number) + "th")







