# -*- coding: utf-8 -*-
"""Unit3_NumPy_Assignment_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xI2i6mtsxLu6EKYiaTkP5OY2BRX7cxFW

<a href="https://colab.research.google.com/github/niteen11/lagcc_data_analytics_micro_credential/blob/master/Unit%203%20-%20Python%20Advanced/Assignments/Unit3_NumPy_Assignment_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Unit 3 - Advanced Python - NumPy - Assingment #1

## 1. Environment Set up
"""

import numpy as np

#Dataset from summer Olympic London, year 2012
np_olympic_country = np.array(['GBR','China','RUS','US','KOR','JPN','GER'])
np_olympic_country_Gold = np.array([29,38,24,46,13,7,11])
np_olympic_country_Silver = np.array([17,28,25,28,8,14,11])
np_olympic_country_Bronze = np.array([19,22,32,29,7,17,14])



"""## 2.	Find country with maximum gold"""

max_element = np.amax(np_olympic_country_Gold)
print('Max gold from np_olympic_country_Gold:' , max_element)
max_gold = np.where(np_olympic_country_Gold == np.max(np_olympic_country_Gold))

np_olympic_country[max_gold]

"""## 3.	Find countries with more than 20 gold medals"""

#countries with 20 = < gold
gold_gatherers = np.where(np_olympic_country_Gold > 20)
np_olympic_country[gold_gatherers]







