# -*- coding: utf-8 -*-
"""Unit2_List_Assignment_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1r-ct47kzVl2vskryQNJhyHHhgjI7G-Wz

<a href="https://colab.research.google.com/github/niteen11/lagcc_data_analytics_micro_credential/blob/master/Unit%202%20-%20Python%20Fundamentals/Assignments/Unit2_List_Assignment_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Intrdouction to Python - List - Assingment #2

## 1.Create a list of 5 of your favorite tv shows.  ?
"""

#create a list for 5 tv shows
List = [ "Seinfeld", "Breaking Bad", "The Sopranos", "Friends", "Dexter" ]



"""## 2.	Print the list in its original order"""

#print the created list
print(List[0])
print(List[1])
print(List[2])
print(List[3])
print(List[4])



"""## 3.	Use the sorted() function to print the list in alphabetical order.  How is sorted() different from sort()?"""

#sort list using sorted()
sorted(List)

#list.sort() sorts the list and replaces the original list, whereas sorted(list) returns a sorted copy of the list, without changing the original list.

"""## 4.	Print out your original list."""

print(List)



"""## 5.	Used sorted() to print your list in reverse alphabetical order."""

#sort reverse ABC order using sorted()

print(sorted(List, reverse=True))



"""## 6.	Create a message indicating how many favorite TV shows you have – use the len() function."""

#use len() to see how many shows I have
#create a message



int(len(List))

print("I have " + str(int(len(List))) + " favorite TV shows")

